ember-cli/ember-twiddle

app/components/dummy-demo-app.js
app/gist/controller.js
app/gist/new/route.js
app/gist/template.hbs
app/models/gist-file.js
app/services/ember-cli.js
tests/acceptance/gist-test.js

This allows for CSS styling, and creates a default styles/app.css for an easier start to editing.
This fixes issue #52

Support styles (fixes issue #52)

---

app/gist/template.hbs
app/index.html

Thanks guys, this tool works great!

Fix additional links to point to the new repo

---

app/gist/controller.js
app/gist/new/route.js
app/models/gist.js
package.json

Fork a gist using Github API

---

app/components/file-editor-column.js
app/gist/controller.js
app/gist/template.hbs

`activeEditor` isn't a component instance anymore, but a column number.

focus first column editor on file creation

---

app/gist/edit/route.js

Handle secret or missing gists

---

app/gist/edit/route.js

Fix bug in missing_gist

---

app/gist/controller.js
tests/unit/gist/controller-test.js

Confirm before deleting a twiddle

---

app/components/dummy-demo-app.js
app/gist/controller.js
app/services/ember-cli.js
blueprints/config_environment.js
blueprints/router_initializer.js
ember-cli-build.js
tests/helpers/run-gist.js

Use sandbox + srcdoc and postMessage for updating the url.

---

README.md

They just clutter up the PR without adding value, and can sometimes be confused with an acceptance of the PR.

Please don't encourage +1s

---

app/mirage/config.js
app/mirage/factories/user.js
app/mirage/scenarios/default.js
tests/acceptance/gist-test.js
tests/helpers/run-gist.js

Mock the logged in user

---

app/gist/controller.js
app/gist/template.hbs
app/styles/app.scss

fixes https://github.com/ember-cli/ember-twiddle/issues/97

Rename "Autorun" to "Live Reload"

---

.watchmanconfig

Adds `.watchmanconfig` that now comes with ember-cli
https://github.com/ember-cli/ember-cli/pull/4124

Add .watchmanconfig

---

app/components/saved-state-indicator.js
app/gist/template.hbs
app/templates/components/saved-state-indicator.hbs
tests/integration/components/saved-state-indicator-test.js

Extract saved-state-indicator component

---

app/index.html

- Updates page title
- Adds a meta description so it doesn't show up in search results like in the screenshot below

Update page title and meta description

---

blueprints/twiddle.json
bower.json
package.json

Update Ember to 1.13.8 and Ember Data to 1.13.9

---

app/gist/controller.js
tests/acceptance/gist-test.js

Fix file menu shows deleted file bug

---

app/gist/controller.js
app/gist/route.js
app/services/ember-cli.js

Fix for https://github.com/ember-cli/ember-twiddle/issues/158

replaces Ember.String.fmt with template strings (fixes #158)

---

app/templates/components/editor-mode-menu.hbs

Fixes https://github.com/ember-cli/ember-twiddle/issues/163

alter text from mode to keystroke mode

---

app/gist/controller.js
tests/acceptance/gist-test.js
tests/unit/gist/controller-test.js

Fix cannot add components in pods format when adding just js file

---

app/components/file-tree.js
app/styles/app.scss
app/templates/components/file-tree.hbs
tests/integration/components/file-tree-test.js

Add ability to expand and collapse all to file tree

---

app/gist/route.js
app/serializers/application.js
app/serializers/gist.js

As to why this new API is any better, I don't know. Just seems more confusing to me.

Update to new serializer API

---

app/components/dummy-demo-app.js
app/components/twiddle-panes.js
app/styles/app.scss
package.json

Attempt to fix mobile CSS

---

app/gist/controller.js
app/routes/gist-base-route.js

Fix New Twiddle doesn't change pane content

---

app/index.html

Pretty sure this is the only thing missing to include the favicon.ico

link the Favicon

---

app/components/saved-twiddles-row.js
app/serializers/gist.js
app/twiddles/route.js

Apply @stefanpenner 's comments to PR #200

Follow up to Show Twiddles List

---

app/services/ember-cli.js
tests/acceptance/escape-test.js

Allow handlebars escaped moustache tags

---

app/components/file-tree.js
tests/integration/components/file-tree-test.js

Fix cannot open file tree if folder contains only folders

---

app/templates/components/user-menu.hbs

Correct GitHub's case

---

app/styles/app.scss

[UI] highlight current row in list of twiddles

---

blueprints/twiddle.json

Update twiddle.json ember version

---

app/services/ember-cli.js
tests/unit/services/ember-cli-test.js

Update ember-template-compiler when ember dependency is updated

---

blueprints/twiddle.json

This makes it obvious how to add feature flags to a new twiddle at the cost of some extra bytes per twiddle.

Add empty FEATURES to twiddle.json

---

app/application/route.js
app/components/title-input.js
app/gist/controller.js
app/gist/route.js
app/gist/template.hbs
app/templates/components/title-input.hbs
app/twiddles/route.js
package.json
tests/acceptance/gist-test.js
tests/acceptance/update-title-test.js

Show gist description in document title

---

scripts/travis-deploy.sh

Fix travis deploying to production on non master branch push

---

app/styles/app.scss
app/templates/components/user-menu.hbs

… to ensure that the URL is correct.

Changed GH logo to be a bg image in css rather than inline image

---

app/styles/app.scss
app/templates/components/user-menu.hbs
ember-cli-build.js

GitHub logo

---

app/services/dependency-resolver.js
tests/unit/services/dependency-resolver-test.js

Fixes mixed use warning when using channels

Use caching proxy server ember.alexspeller.com for channels

---

app/app.js
app/services/ember-cli.js
bower.json
ember-cli-build.js
package.json
tests/helpers/resolver.js

Fixes additional deprecation warnings for container-debug-adapter.

Update ember-resolver to NPM version.

---

bower.json
package.json

Upgrade Ember and Ember Data to 2.1

---

app/gist/controller.js
config/environment.js
tests/acceptance/routing-test.js

Reflect current route in query parameter

---

app/adapters/application.js

Send modelName, not typeKey, to serializerFor

---

app/gist/controller.js
tests/acceptance/columns-test.js

Specify open files via query paramter

---

app/services/ember-cli.js
bower.json
ember-cli-build.js
package.json

Use latest ember-resolver addon instead of legacy bower_component

---

app/services/dependency-resolver.js

This also updates the latest version for the 2.2. series to 2.2.1
**TODO**

Ember-Data 2.3.0 has been released

---

app/torii-adapters/application.js

Fixes #313
I'm not actually sure how this worked before ¯\_(ツ)_/¯
but I must have triggered some error when changing `this.store` to `this.get('store')` in my previous PR
@rwjblue @Gaurav0 I'll try to add tests to this later on (or as a seperate PR) but since this problem seems quiet urgent I wanted to make the fix available asap.

Fix login issue

---

app/components/file-menu.js
app/gist/controller.js
app/gist/template.hbs
app/services/ember-cli.js
app/templates/components/file-menu.hbs
ember-cli-build.js
tests/acceptance/gist-test.js

This makes it so easy to add a unit test for a controller, route, or service!

Initial unit test blueprints

---

ember-cli-build.js

Minor fix for previous PR

---

app/components/file-menu.js
app/gist/controller.js
app/gist/template.hbs
app/services/ember-cli.js
app/templates/components/file-menu.hbs
blueprints/start-app.js
ember-cli-build.js
tests/acceptance/gist-test.js

This makes it so easy to add an acceptance test!
Part of issue #305

Initial Acceptance Test Blueprints

---

app/gist/controller.js
package.json
tests/acceptance/columns-test.js

Use query parameter to reflect whether file tree is shown

---

app/gist/controller.js
tests/acceptance/columns-test.js
tests/acceptance/gist-test.js

Change defaults to make twiddle look like an editor

---

app/components/file-menu.js
app/gist/controller.js
app/gist/template.hbs
app/services/ember-cli.js
app/templates/components/file-menu.hbs
ember-cli-build.js
tests/acceptance/gist-test.js

This makes it so easy to add a component integration test!
This completes issue #305

Initial Integration Test Blueprints

---

app/gist/route.js

Add error message for an empty file

---

app/gist/route.js

Fix new route url parameter

---

app/services/ember-cli.js
tests/acceptance/import-mixin-test.js

Fix importing mixins by using amdStrict option

---

app/gist/controller.js
app/routes/gist-base-route.js
app/services/ember-cli.js
blueprints/twiddle.json
bower.json
package.json
tests/acceptance/columns-test.js
tests/acceptance/use-pods-test.js
tests/helpers/wait-for-loaded-iframe.js

New files do not use pods by default unless new option is set

---

app/components/better-checkbox.js
app/components/file-editor-column.js
app/components/file-menu.js
app/components/run-or-live-reload.js
app/components/user-menu.js
app/gist/template.hbs
app/templates/components/run-or-live-reload.hbs
app/twiddles/template.hbs
package.json
tests/integration/components/better-checkbox-test.js
tests/integration/components/file-menu-test.js
tests/integration/components/run-or-live-reload-test.js
tests/integration/components/user-menu-test.js

Replaces all remaining traditional actions with closure actions

Use ember-route-action-helper

---

app/gist/new/route.js
app/gist/route.js
app/routes/gist-base-route.js
app/templates/components/saved-state-indicator.hbs
tests/acceptance/gist-test.js
tests/acceptance/twiddles-test.js

Confirmation before unloading unsaved twiddle

---

app/components/file-menu.js
app/components/versions-menu.js
app/mixins/dropdown-submenu-fix.js
app/templates/components/file-menu.hbs
app/templates/components/versions-menu.hbs
ember-cli-build.js
vendor/bootstrap-dropdown-submenu-fix.css

Fix bootstrap nav submenus

---

app/gist/route.js

Fix showing unsaved confirmation while saving

---

app/components/file-tree.js
app/templates/components/file-tree.hbs
tests/integration/components/file-tree-test.js

Update file tree when renaming

---

app/models/gist-file.js
app/models/gist.js

Fix weird bug where deleted record not removed from hasMany relationship

---

app/styles/_main.scss
app/styles/_toolbar.scss
app/styles/_variables.scss

Fixes background part of #377 
Mobile view screenshot:

Fix mobile dropdown css

---

app/gist/route.js
mirage/config.js
tests/acceptance/delete-test.js
tests/acceptance/gist-test.js
tests/acceptance/save-test.js
tests/unit/routes/gist-test.js

Ensure deleting a twiddle results in new twiddle + tests

---

app/components/file-tree.js
config/environment.js
tests/integration/components/file-tree-test.js

Automatically expand all the file tree if number of files is low

---

app/components/file-editor-column.js
app/components/main-gist.js
tests/acceptance/gist-test.js

Fixes https://github.com/ember-cli/ember-twiddle/issues/448

Fix editing codemirror does not update gist

---

app/services/dependency-resolver.js
app/services/twiddle-json.js

Support multiple Ember versions in addon builder

---

app/adapters/gist-file.js
app/gist/edit/revision/route.js
mirage/config.js

Fix issue on save with non-unique filenames

---

app/components/dummy-app.js
app/services/dependency-resolver.js
app/services/twiddle-json.js
blueprints/twiddle.json
bower.json
mirage/config.js
mirage/fixtures/addon.js
mirage/fixtures/ember-data.js
package.json
tests/acceptance/addons-test.js
tests/acceptance/run-now-test.js
tests/unit/services/ember-cli-test.js
vendor/ember-data-shims.js

Run ember-data as addon by default

---

app/services/twiddle-json.js

there is no need for `try.. catch` inside promise it will be caught anyway http://jsbin.com/cemetopifo/edit?html,js,output

removed redundant try catch

---

app/services/ember-cli.js
blueprints/twiddle.json
package.json
tests/.jshintrc
tests/acceptance/gist-test.js
tests/acceptance/git-revision-test.js
tests/helpers/wait-for-loaded-iframe.js
tests/helpers/wait-for-unloaded-iframe.js
tests/test-helper.js
tests/unit/services/ember-cli-test.js
yarn.lock

Hoping I got them all this time. :)

Try to fix flakey tests again

---

app/services/resizeable-columns.js

Related to #376
A small refactor which was suggested to improve the code climate.

Refactor mouse events in resizeable columns

---

.dockerignore
CONTRIBUTING.md
docker-compose.yml
entrypoint.sh

Adding support for people to use `Docker` to run the server.

Adding docker support

---

CONTRIBUTING.md

updates contribution guide w.r.t. running gatekeeper referred in #620

updates contribution guide

---

app/components/main-gist.js
app/routes/gist.js
app/templates/components/gist-header.hbs
app/templates/components/main-gist.hbs
app/templates/components/saved-state-indicator.hbs
app/templates/gist.hbs
package.json
tests/acceptance/code-comment-test.js
tests/acceptance/run-now-test.js
tests/acceptance/save-test.js
tests/helpers/start-app.js
tests/unit/components/main-gist-test.js
yarn.lock

Run now - `Cmd/Ctrl + Enter`
Save gist - `Cmd/Ctrl + S`
related to #517 and base to #34

adds keyboard shortcuts for `run now` and `save`

---

.gitignore
app/services/ember-cli.js

For https://github.com/ember-cli/ember-twiddle/issues/625

Support ember-decorators

---

app/adapters/gist-file.js
app/models/gist-file.js
config/environment.js
tests/acceptance/columns-test.js
tests/acceptance/gist-test.js

fixes: https://github.com/ember-cli/ember-twiddle/issues/658

feat: Support files with multiple periods in the filepath.

---

app/styles/_dropdown.scss
app/templates/components/file-menu.hbs

@knownasilya Didn't notice this bug until after I merged.

Fix add submenu

---

app/mixins/files.js
app/services/twiddle-json.js

Fix for the issue https://github.com/ember-cli/ember-twiddle/issues/715

Fix content while creating a "js only" component

---

blueprints/twiddle.json
ember-cli-build.js
package.json
yarn.lock

Change optional features defaults in twiddle.json to be the ones used in Ember Octane.

change defaults in twiddle.json to octane

---

app/adapters/user.js
package.json
yarn.lock

work around changes to github api

Fix login broken
