Brocfile.js
app/adapters/application.js
app/adapters/user.js
app/application/template.hbs
app/components/file-editor-column.js
app/gist/controller.js
app/gist/edit/route.js
app/gist/new/route.js
app/gist/route.js
app/gist/template.hbs
app/index.html
app/models/gist-file.js
app/models/gist.js
app/models/user.js
app/router.js
app/serializers/gist.js
app/styles/app.scss
app/templates/components/file-editor-column.hbs
app/torii-adapters/application.js
bower.json
config/environment.js
package.json

[WIP] Implement new UI

---

app/gist/controller.js
app/gist/template.hbs
app/services/ember-cli.js
tests/acceptance/gist-test.js

This allows existing Ember Twiddle gists without a router.js to continue to work by making router.js optional. Users can now add a router through a blueprint. This also lets them conveniently reset the router by deleting and adding a new one.
Fixes issue #55

Make router.js optional; add router blueprint (fixes issue #55)

---

app/gist/controller.js
bower.json

1 failing test, will investigate.

bump to ember 1.13.4

---

app/gist/controller.js
app/gist/template.hbs
app/styles/app.scss

Create an option to turn off autorun

---

app/styles/app.scss

Monaco only ships with [OS X](https://en.wikipedia.org/wiki/Monaco_(typeface)) and is currently used as the CodeMirror editor font-family.
This commit adds a fallback to the default browser monospace font if Monaco isn't available.

Adds CodeMirror font-family fallback to monospace

---

CONTRIBUTING.md

To help anyone who wants to contribute to set up the project locally

extend dev setup instructions to include gatekeeper

---

app/services/ember-cli.js
blueprints/twiddle.json

Use external ember-template-compiler to allow for older versions of Ember.js
Fixes Issue #81

Use external ember-template-compiler

---

tests/.jshintrc
tests/acceptance/minimal-test.js
tests/acceptance/routing-test.js
tests/helpers/run-gist.js
tests/helpers/start-app.js
tests/test-helper.js

Create runGist helper; minimal gist acceptance test

---

app/styles/app.scss

Currently, in the application most of the menu options shows text cursor on hover which does not give us a feeling that it's clickable. 
In this pull request, I have added the hand cursor style for all the drop-down menu options so that it's consistent across the application.

Added hand cursor style for all the menu options

---

app/components/file-menu.js
app/gist/controller.js
app/gist/template.hbs
app/templates/components/file-menu.hbs
tests/integration/components/file-menu-test.js

Extract File menu into a component

---

app/styles/app.scss

This fixes the following issue on canary:

Quick fix for cutoff title

---

app/index.html

After @miguelcobain's great work updating styles I think we could get rid of the "Fork me on GitHub" ribbon. IMHO it's way too big and distracting. We're already linking to the repo and issue tracker from the top menu. Thoughts?

Remove GitHub fork ribbon

---

.jshintrc
app/adapters/application.js
app/components/dummy-demo-app.js
app/components/file-editor-column.js
app/gist/controller.js
app/gist/new/route.js
app/lib/resize-mixin.js
app/models/gist-file.js
app/models/gist.js
app/models/user.js
app/routes/gist-base-route.js
app/services/ember-cli.js
app/torii-adapters/application.js

Adds missing imports of `Ember` and removes usage of global `Em`

Remove usage of global `Em`

---

app/components/user-menu.js
app/gist/template.hbs
app/templates/components/user-menu.hbs
tests/integration/components/user-menu-test.js

Extract user-menu component

---

.travis.yml
app/templates/application.hbs
package.json
public/crossdomain.xml

Updates ember-cli to 1.13.7
I left out the ember-content-security-policy npm package that was added because I saw https://github.com/ember-cli/ember-twiddle/pull/109

Bump ember-cli to v1.13.7

---

app/components/file-menu.js
app/gist/controller.js
app/gist/route.js
app/gist/template.hbs
tests/integration/components/file-menu-test.js

Fork twiddle should save changes

---

app/components/editor-mode-menu.js
app/components/file-editor-column.js
app/components/file-menu.js
app/gist/controller.js
app/gist/template.hbs
app/models/settings.js
app/models/user.js
app/templates/components/editor-mode-menu.hbs
app/templates/components/file-editor-column.hbs
app/templates/components/file-menu.hbs
ember-cli-build.js
package.json
tests/integration/components/editor-mode-menu-test.js
tests/unit/models/settings-test.js

fixes https://github.com/ember-cli/ember-twiddle/issues/48
~~Right now ember-twiddle is dependent on a fork of ivy-codemirror until https://github.com/IvyApp/ivy-codemirror/pull/5 is merged in.~~
~~This is additionally dependent on https://github.com/IvyApp/ivy-codemirror/pull/7 being merged, which adds support for importing the additional key maps. It is currently working while using my fork that includes the changes in both of those PRs but could also be made to work by manually importing those key map files via bower.~~
It would probably also be cool to persist these settings somewhere but I'm not sure where you would want that done. Maybe in localStorage or a specially named gist?

Add support for vim, emacs, and sublime key maps

---

app/components/file-menu.js
app/gist/controller.js
app/gist/template.hbs
app/helpers/error-messages.js
app/templates/components/file-menu.hbs
tests/acceptance/gist-test.js
tests/helpers/util.js

Takes care of issue #35.
One difference from discussions there is that if user enters file extension, get snarky error msg instead of stripping it off :-), but this can be changed if the latter felt better.
Tests to come.

add component (both js and hbs) Add File choice

---

app/components/file-menu.js
app/gist/route.js
app/models/gist.js
app/serializers/gist.js
app/templates/components/file-menu.hbs
tests/integration/components/file-menu-test.js

1. The fork menu option now no longer appears unless you do not own the gist
2. The save option forks if you do not own the gist
Relevant to issue #153

Improve Forking and Saving

---

app/styles/app.scss

Before:
After:
This probably looks really different with different avatars. My ears always get cut off at the tips.

stops the corners of user avatar from being cut off

---

app/components/title-input.js
app/templates/components/title-input.hbs
package.json

press enter to focus out
clear default text on focus in
replace default text on focus out

better title input

---

app/gist/controller.js
tests/acceptance/columns-test.js

Small change, but currently when page loads and code panes are greyed out, can give impression that twiddle is disabled.  This seeks to highlights that is editable and people can jump right in.

set first column active on load

---

app/gist/controller.js
app/services/ember-cli.js
tests/acceptance/gist-test.js

Use pod format consistently

---

app/components/file-tree.js
tests/integration/components/file-tree-test.js
tests/unit/gist/controller-test.js

Fix tree does not nest than one level

---

bower.json
package.json

This should solve the multitude of issues / PRs that have tried to fix this.
tldr; the changes made to autoresize detect when a font family has loaded and reschedules the measurement code.

Fix twiddle title being cut off by updating ember-autoresize

---

app/services/ember-cli.js
app/templates/components/file-menu.hbs
ember-cli-build.js
tests/acceptance/gist-test.js

Adds a service blueprint. Also sorts the blueprint list in `ember-cli-build.js` alphabetically (let me know if you'd prefer a separate commit).

Add service blueprint

---

blueprints/twiddle.json
tests/acceptance/dependency-test.js
tests/acceptance/no-compiler-test.js
tests/acceptance/routing-test.js

Also reduces deprecation warnings during tests.

Update default Ember to 1.13.10 and default Ember Data to 1.13.13

---

app/components/file-menu.js
app/gist/new/controller.js
app/gist/new/route.js
app/gist/route.js
app/gist/template.hbs
app/templates/components/file-menu.hbs
tests/acceptance/gist-test.js
tests/integration/components/file-menu-test.js

If a gist owned by the authenticated user is shown, a new menu item
"Copy Twiddle" allows to copy the current files into a new Twiddle. Note
that the newly created Twiddle is not yet saved.
By this, Twiddles (e.g. Ember setup for a specific version) can be used
as a starting point without having to re-setup the whole Twiddle again
and again.
---
This addresses #78 and https://github.com/ember-cli/ember-twiddle/pull/157#issuecomment-138380066.

Add possibility to copy own twiddle

---

app/gist/edit/copy/route.js
app/gist/new/route.js
app/router.js
tests/acceptance/gist-test.js

This PR creates a new route `/:gist/copy` which is a shortcut to copy a gist into a new Twiddle.
This addresses #216.

Copy gist route

---

app/services/ember-cli.js
tests/acceptance/ember-env-test.js

The value of the top-level `EmberENV` key of twidde.json is set as
`window.EmberENV` in the Twiddles' application index.html. By this,
Twiddle can be created which make use of features in Ember, which are
put behind a feature flag:
// twiddle.json
{
"EmberENV": {
"FEATURES": {
"ember-htmlbars-component-generation": true
}
}
}
---
This addresses #188

Add possibility to specify EmberENV in twiddle.json

---

app/styles/app.scss

This makes it consistent with the profile pic rendered on GitHub.
Subtle change but makes the appearance more smoother IMHO.
---
Before
After

Add border-radius to profile pic of logged in user

---

app/services/ember-cli.js
blueprints/index.html
tests/.jshintrc
tests/acceptance/gist-test.js
tests/acceptance/run-now-test.js
tests/helpers/run-gist.js
tests/helpers/wait-for-loaded-iframe.js
tests/test-helper.js

The used `{{dummy-demo-app}}` component only reloads the application if
the passed `html` property changes. If nothing changes in the underlying
app, succeeding clicks on "run now" will do nothing, as the HTML doesn't
change.
To force enable the reload of the application, this commit adds a new
`<meta name="build-at" >` tag, which' value is set to the milliseconds
since the Unix Epoch. By this, the HTML changes everytime the app is
build and now the "run now" button always reloads the application.
---
This addresses #220

"Run now" reloads app

---

app/components/dummy-demo-app.js

Allow `alert` and `confirm` in twiddles

Allow modals (alert, confirm) in ember-twiddle

---

app/components/versions-menu.js
app/gist/controller.js
app/gist/template.hbs
app/services/dependency-resolver.js
app/services/ember-cli.js
app/templates/components/versions-menu.hbs
tests/acceptance/dependency-test.js
tests/integration/components/versions-menu-test.js
tests/unit/services/dependency-resolver-test.js
tests/unit/services/ember-cli-test.js

- allow to specify version instead of full URL for `ember`, `ember-template-compiler` and `ember-data`
- allow release channels: `release`, `beta` and `canary`
- add menu item to update version for `ember` and `ember-data` via UI
---
---
---

Dependencies refactoring

---

app/components/user-menu.js
app/gist/route.js
app/gist/template.hbs
app/styles/app.scss
app/templates/components/file-menu.hbs
app/templates/components/user-menu.hbs
app/twiddles/template.hbs
tests/acceptance/twiddles-test.js
tests/integration/components/file-menu-test.js
tests/integration/components/user-menu-test.js

This makes the look of `/twiddles` consistent with the other look by rendering the toolbar. Also, the user menu now has a link which navigates to the `/twiddles` route.
---
*Before*
---
*After*
---
Added *My Saved Twiddles* menu item in user menu
---
*In action*

Overhaul /twiddles

---

app/twiddles/route.js
tests/acceptance/twiddles-test.js

A logout on the /twiddles route navigates to the page where a new, empty
twiddle is shown.

Implement logout on /twiddles route

---

app/gist/route.js

This previously caused an error when saving because `this` wasn't being preserved.
Prior error:

Use arrow function to preserve this.

---

app/gist/route.js

Attempt to always show a loud error if saving or forking fails.
Issue #234

Loud save error

---

app/components/file-menu.js
app/gist/controller.js
app/gist/template.hbs
app/services/ember-cli.js
app/templates/components/file-menu.hbs
ember-cli-build.js
tests/acceptance/gist-test.js
tests/unit/services/ember-cli-test.js

This PR also adds a way to replace arbitrary properties in the blueprint
content when calling `buildProperties` in the emberCLI service.
Closes #191
Thanks @SaladFork for your Services PR, which I used to bounce off of.

Add 'helper' blueprint

---

package.json
tests/acceptance/twiddles-test.js

Executing the tests locally threw an error due to run-loop issues with `ember-resize`. This has been fixed upstream in https://github.com/tim-evans/ember-autoresize/pull/26.
---
Parsing an empty string for `twiddle.json` throws an error at the end of the `visting /twiddles` acceptance test, which somehow isn't failing the test but the error is logged in the console of Web Inspector.

Fix failing tests

---

app/components/file-menu.js

Fixes #242. The embed markup includes a wrapper div and some minimal inline styles on both it and the iframe to allow it to use the full width of the containing element. I chose 16:9 ratio. I tried 4:3 but found it to be too tall. This could be configurable, although it would mean an extra step for the user in creating the embed code.

Added wrapper around iframe to make it responsive.

---

app/styles/app.scss

Fixes #246.
If a user has not uploaded an avatar to GH they are assigned a default image. This image is returned to Twiddle as 240x240. This PR forces the image to be resized in that case.

set explicit w&h on .user-avatar img

---

app/components/user-menu.js
app/gist/controller.js
app/gist/template.hbs
app/templates/components/user-menu.hbs
tests/integration/components/user-menu-test.js

This changes the link in the help menu to point to the release notes of the current version. Example: https://github.com/ember-cli/ember-twiddle/releases/tag/0.4.14
---
Note that the link will be broken in canary and in development, but I think that is acceptable...

Link to GH release page of current version

---

app/twiddles/template.hbs

The version is read from the config inside the {{user-menu}} component,
so there is no need to pass it.
Also, this is a leftover from 55e5f895f161b1b23efc4a513b7abc66baaf5f64,
where the {{user-menu}} has been added to the toolbar but there is no
`version` property set on the controller.
---
This fixes the weird `Ember Twiddle v` menu item on `/twiddles`:

Don't set version for {{user-menu}} in twiddles template

---

package.json

This version removes the noise produced by logging the current revision
in an initializer.
---
Credits go to @joostdevries for implementing this upstream in rwjblue/ember-git-version#6.

Bump version of ember-git-version to 0.1.0

---

tests/helpers/run-gist.js

Still one more to fix (container-debug-adapter).

Fix initializer warning when testing against Ember 2.1.

---

app/gist/controller.js
app/services/ember-cli.js
tests/acceptance/routing-test.js
tests/helpers/run-gist.js
tests/helpers/wait-for-loaded-iframe.js

Also improves api of runGist to allow for specifying gist parameters other than files.

Allow user to specify initial route via query parameter

---

app/styles/app.scss
app/templates/components/user-menu.hbs

This allows clicking the icons (after login, and before) to
access the actions that they provide.
So the github icon is now clickable for signin and the user's avatar for
opening the user menu.

Include icons in user menu

---

tests/acceptance/routing-test.js

This fixes the test timing out in Chrome but needing to wait in PhantomJS or other browsers. Seems like a race condition.

Fix routing test timing out in chrome

---

app/components/file-tree.js
app/templates/components/file-tree.hbs
package.json

Note: Some of the jstree related tests still sporadically fail in Chrome. @ritesh83 can you please look into this?

Update ember-cli-jstree to fix 'calling set on destroyed object' errors in Chrome

---

app/services/ember-cli.js
tests/unit/services/ember-cli-test.js

This is used internally within Ember to allow local lookups in the future, it also mirrors ember-cli-htmlbars transpilation a bit better.

Provide moduleName for transpiled templates.

---

app/services/ember-cli.js
tests/unit/services/ember-cli-test.js

Prior to this, inclusion of a backtick in a template would throw an
error.

Escape backticks in templates.

---

app/components/file-editor-column.js
app/gist/controller.js
app/gist/template.hbs
package.json
tests/integration/components/file-editor-column-test.js

This fixes issue #290, but it depends on [these](https://github.com/IvyApp/ivy-codemirror/compare/19f4d62e4e6afe9b19c31fe919a7809ce827c56a...piotrpalek:pass-params) changes to codemirror.

Fix navigation reload

---

app/models/gist-file.js
tests/unit/models/gist-file-test.js

This fixes #237. The `registerDeleteOnGist` observer isn't always called, that's the reason why deleting doesn't work properly. 
I replaced it by overriding the `deleteRecord` method on the model which calls the neccesary code.
I'm assuming the observer didn't work because `isDeleted` is a computed property which isn't consumed anywhere, I tried fixing it by calling `this.get('isDeleted')` in the init method but that didn't really fix the issue completely (it seemed to help a little, didn't test it too much though).
Anyway I think depending on the `isDeleted` flag + observer might not be the best way to accomplish this to begin with.

Fix file deletion

---

app/gist/template.hbs
app/styles/_toolbar.scss
app/templates/components/file-menu.hbs
package.json

Fixes #294 
:warning: Still WIP
* Move title out of the collapsed menu
* Improve collapse button colors and position
* Make collapse menu items bigger for better mobile support
* Fix collapse menu item positioning and add break
* Fixes dropdown menu positioning and styles

Cleanup Responsive Navbar Menu

---

app/services/ember-cli.js
blueprints/twiddle.json
ember-cli-build.js
package.json
tests/unit/services/ember-cli-test.js

This is for issue #178. We will still need some way in the UI to enable / disable testing "mode". Right now, it will be an option in twiddle.json, which also persists it.
@rwjblue @stefanpenner @joostdevries @alexspeller Please let me know what you think of my approach.
Screenshot:

Make it easier to do Testing

---

ember-cli-build.js

Fixes issue #311 
Note: We need sauce tests (or similar) to run the tests in Firefox in order to write an automated test to ensure that this works. Checked locally.

Fix broken routing in Firefox

---

blueprints/application_controller.js

Minor fix to add a space after `appName:`

add space after colon

---

app/services/ember-cli.js
package.json

This adds the babel plugin to the pipeline, which makes it possible to
use `import hbs from "htmlbars-inline-precompile";`. This is helpful for
writing component integration tests using ember-twiddle.
This addresses #326.
---
I tried to add a blueprint for a component test, but we can't import the one from `ember-cli` since [its' template uses `if`s](https://github.com/ember-cli/ember-cli/blob/v2.3.0/blueprints/component-test/files/tests/__testType__/__path__/__test__.js), which are [not yet supported within `ember-twiddle`](https://github.com/ember-cli/ember-twiddle/blob/v0.6.0/app/services/ember-cli.js#L158-L165)...

Add babel-plugin-htmlbars-inline-precompile to babel pipeline

---

app/twiddles/route.js

Looks like gist.github.com is now only returning 30 gists by default. This increases that to a max of 100 gists. To do more, we will have to implement pagination.

Get more than 30 twiddles

---

app/services/dependency-resolver.js
app/services/ember-cli.js

**VERY WIP**
Adds support for using addons in `twiddle.json` like this:
```json
{
"addons": {
"ember-tooltips": "latest"
}
}
```
This works by requesting a combo of addon + addon version + ember version from an API which in turn redirects to an S3 bucket where the built addons are stored. If the addon is not built yet, it will trigger a build in the background (using lambda).
Build process:
- https://github.com/joostdevries/twiddle-backend/blob/master/addon-builder/ember-blueprints/1.13.15/ember-cli-build.js
- https://github.com/joostdevries/twiddle-backend/blob/master/addon-builder/index.js
Features:
- Will use NPM version resolving (so you can use "latests" or semver logic in `twiddle.json`)
- Will try to build the addon if it's not in our S3 bucket yet
- Will include both CSS + JS
- …

[WIP] Addon support

---

app/services/dependency-resolver.js

Previously, the dependencies were ordered like:
After this change, the following order is used:

Make dependencies order chronologically.

---

app/styles/_toolbar.scss

typo causes image not to show up when CSS is minified and background properties are combined

fixed header position typo

---

app/mixins/app-builder.js
app/services/dependency-resolver.js
mirage/config.js
mirage/fixtures/addon.js
tests/acceptance/addons-test.js

using power of ember-concurrency

Auto refresh after addon build completes

---

app/components/file-menu.js
app/gist/edit/revision/copy/route.js
app/gist/edit/revision/route.js
app/gist/template.hbs
app/templates/components/file-menu.hbs
app/templates/components/gist-header.hbs
app/templates/components/main-gist.hbs
tests/acceptance/git-revision-test.js

This adds the ability to copy a previous revision of an existing gist, yours or not, into a new gist.
This also removes the fork option for gist revisions, as Github does not provide the ability to fork from a previous revision of a gist.

Add ability to copy gist revision to new gist

---

blueprints/model.js
ember-cli-build.js

Since the model blueprint from ember-cli-legacy-blueprints contains
custom logic for the import statements in the blueprints' index.js and
ember-twiddle doesn't support this (yet), we create our own model
blueprint inside ember-twiddle.
---
The currently generated model file using the blueprint from
ember-cli-legacy-blueprints looks like this (note the lacking import
for `Model`):
```js
export default Model.extend({
});
```

Use custom model blueprint

---

app/templates/components/file-editor-column.hbs
bower.json

Codemirror options are now specified via hash instead of individual properties since ivy-codemirror 2.0. This broke features.

Fix codemirror options

---

app/services/dependency-resolver.js
app/services/twiddle-json.js
blueprints/twiddle.json
ember-cli-build.js
tests/acceptance/addons-test.js
tests/acceptance/routing-test.js
tests/acceptance/use-pods-test.js
tests/unit/services/dependency-resolver-test.js
tests/unit/services/twiddle-json-test.js

The idea here is to use the same version of ember-testing.js as ember.js, just like with ember-template-compiler.js
Fixes #468

Fix integration tests broken by upgrade to Ember 2.7

---

app/components/main-gist.js
app/services/ember-cli.js
app/services/twiddle-json.js
app/styles/_output-pane.scss
app/templates/components/gist-body.hbs
app/templates/components/main-gist.hbs

- disables app running alongside tests, now either the app runs or the tests
- added `legacy-testing` option which when enabled restores the previous behavior
- added "Run Tests" button, which switches the `enable-testing` property in `twiddle.json`
- when clicking "Run Tests" it ensures that test helper files are created
- made some small code cleanups (removed usage of `this.attrs` in the `gist-body` template, use spread syntax for calling super)
[Demo here](http://twiddlefork.herokuapp.com/34a8cd8babf1d7aa2c1a016188756d23?openFiles=tests.helpers.destroy-app.js%2C)

Twiddle testing

---

app/components/twiddle-panes.js
app/styles/_output-pane.scss
app/styles/_toolbar.scss
app/styles/_twiddle-panes.scss
app/templates/components/gist-body.hbs
app/templates/components/gist-header.hbs
tests/acceptance/columns-test.js
tests/integration/components/twiddle-panes-test.js
vendor/drags.js

The main issue I was trying to fix is that the "Run Tests" and "Live Reload" checkboxes cover each other when "Live Reload" is deselected:
Before:
After:
Other problems this will fix (discovered while fixing the first issue):
- the header elements are consistently positioned (especially vertically) across all panes (esp. visible for eg. the on "Output" string):
Before:
After:
- [when the tree is hidden and there are 0 editor panes](https://ember-twiddle.com/?fileTreeShown=false&numColumns=0) the page looked broken:
Before:
After:
- I've changed how the file tree looks and behaves, it is no longer resizable and is much smaller which leaves more space for the important stuff (it still expands when the tree shifts to the right due to many items):
Before:
After:
Mobile view (only last screen …

CSS fixes and improvements

---

app/styles/_saved-twiddles.scss

I was expecting to be able to click the SHA and not having any luck.  I had no idea the Twiddle column and Gist column names were actually links I could click.  This makes it a little easier to see where the links are on the page:

Added underlines to saved twiddle links

---

package.json

One step closer to dealing with #483
`ember-cli-sass` includes `node-sass` 4.1.0, which has support for alpine linux

Upgrade ember-cli-sass dependency

---

app/routes/gist.js
app/routes/twiddles.js
app/torii-providers/github-enterprise.js
config/deploy.js
config/environment.js
ember-cli-build.js

This PR is to add github enterprise support so that ember-twiddle can be run privately if required.
Basically, this PR just replaces hard coded strings with reading from environmental variables. I new torii provider for github enterprise was added because the baseUrl and redirectUrl are different for github enterprise distributions.
I talked to @Gaurav0 about this months ago. Takes me a while to get PRs up due to company policy.

adding github enterprise support

---

app/components/user-menu.js
tests/integration/components/user-menu-test.js

Currently the first item in the help menu on the top right of the site links to https://github.com/ember-cli/ember-twiddle/releases/tag/0.11.0 (404) instead of https://github.com/ember-cli/ember-twiddle/releases/tag/v0.11.0. I think this PR will fix it but haven't tested.

Fix help link

---

app/models/settings.js
app/templates/components/editor-mode-menu.hbs
tests/unit/models/settings-test.js

I would like to hit `ctrl-arrow` when editing ember twiddles and have it work. :smiley: 
From the docs: http://codemirror.net/doc/manual.html
> keyMap: string
Configures the key map to use. The default is "default", which is the only key map defined in codemirror.js itself. Extra key maps are found in the key map directory. See the section on key maps for more information.
https://github.com/codemirror/CodeMirror/blob/master/src/input/keymap.js

Enabling default keymap, and setting as default

---

blueprints/mouse_events_initializer.js

There are scenarios where `$` is rebound (e.g. when using [prototype.js](http://prototypejs.org/)).
We should use `jQuery` instead of `$` (it also makes it somewhat more clear what we are doing IMO).

Import `jQuery` instead of using `$`.

---

app/styles/_output-pane.scss

If the dropdown menu is open over the pane resize handle, the menu will unexpectedly close when the mouse reaches the handle.
This fix bumps the z-index back down (a change was made that increased the `z-index` of `.handle`) below that of  `.dropdown-menu`.

Dropdown menu should be higher than handle

---

app/mixins/gist-controller.js
app/services/dependency-resolver.js
app/services/ember-cli.js
app/services/twiddle-json.js

when value returned inside `then` callback there is no need to wrap it with `RSVP.resolve`  it is always resolved unless wrapped in `RSVP.reject`

removed redundant `RSVP.resolve`s

---

blueprints/model.js

The other blueprints all use single quotes styled strings. The model is the only one that differs. This change makes the quote style consistent.

Use single quotes for model blueprints

---

app/templates/components/file-menu.hbs
tests/integration/components/file-menu-test.js

I've deicded to solve this issue by adding an extra menu item instead of writing something like "Move / Rename {{filename}}" or "Move or rename {{filename}} since I think it creates a lot of clutter. This won't help users figure out how to rename. 
Instead rename and move are seperate items of the menu with the same functionality. In my oppinion this provides a better user experience and more clearity.

Fix #557: Adds extra menu item for renaming a file

---

app/components/dummy-app.js
app/mixins/resize.js

I think this bug was introduced with ESLint fixes.

Fix didResize method undefined bug in canary

---

app/services/ember-cli.js
config/targets.js
ember-cli-build.js
package.json
yarn.lock

This will lead to less transpilation (e.g. we can use native async/await now, instead of transpiling).

Migrate to using babel-preset-env.

---

.eslintrc.js
app/app.js
app/initializers/app-initializer.js
app/templates/components/editor-mode-menu.hbs
app/templates/components/gist-header.hbs
app/templates/components/main-gist.hbs
ember-cli-build.js
tests/acceptance/code-comment-test.js
tests/helpers/destroy-app.js
tests/unit/initializers/app-initializer-test.js

- Adds shortcut option to comment javascript code.
- `cmd-/` in sublime mode (codemirror default)
- `alt-;` in emac mode (codemirror default)
- `cmd-/` in default mode ([added in app](https://github.com/ember-cli/ember-twiddle/compare/master...gokatz:code-comment?expand=1#diff-2de9eda1655d499e934e7465e87ca0bdR6))
- Displays selected keystore type
w.r.t. handlebars, maintainer [just added meta data](https://github.com/codemirror/CodeMirror/commit/fbc002f2ba234b91417e086ff1cae0407320c158) to support commenting in handlebar extensions (not released). We can pull once `ivy-codemirror` updates the deps. 
Haven't implemented any tests for the change. Stuck with dynamic rendering of gist in test. Any help will be great.
related to #143

Adds shortcut option to comment javascript code.

---

app/services/ember-cli.js

Include 'transform-object-rest-spread' plugin to fix ES6 object
spread bug.

Fix ember-cli service babelOpts config bug

---

app/components/main-gist.js

When toggling `Run Tests`, we are getting the below console error:
On investigation, I found that `ensureTestStartAppHelperExists` and `ensureTestDestroyAppHelperExists` functions have been removed in this PR: https://github.com/ember-cli/ember-twiddle/pull/702/files#diff-ce45d0a320c9223a3cd12a5591a6584cL8-L19
This PR is to just remove the use of those two functions in the `switchTest` function as it's currently breaking this feature at the moment.

fix broken switch test function
